<?php
/* German translation for qmailforward plugin */

$labels['manage-forward'] = 'Weiterleitungseinstellungen';
$labels['page-title']     = 'Einstellungen Weiterleitungen';
$labels['forward']  = 'Weiterleitungen';
$labels['redirect'] = 'Umleiten an';
$labels['copy']     = 'Kopie senden an';
$labels['on']       = 'Aktiviert';
$labels['off']      = 'Deaktiviert';
$labels['status']   = 'Status:';
$labels['action']   = 'Führe folgende Aktionen mit eingehenden Nachrichten durch:';
$labels['saving']   = 'Speichern...';
$labels['success']  = 'Erfolreich gespeichert';
$labels['failed']   = 'Fehler beim Speichern der Datenbank';
$labels['invalid_email'] = 'Ungültige E-Mail Adresse';
