<?php
/* English translation for qmailforward plugin */

$labels['manage-forward'] = 'Forwarding settings';
$labels['page-title']     = 'Forwarding settings';
$labels['forward']  = 'Forwarding';
$labels['redirect'] = 'Redirect to';
$labels['copy']     = 'Send copy to';
$labels['on']       = 'Enabled';
$labels['off']      = 'Disabled';
$labels['status']   = 'Status:';
$labels['action']   = 'Perform the following actions with incoming messages:';
$labels['saving']   = 'Saving...';
$labels['success']  = 'Saved successfully';
$labels['failed']   = 'Error saving to database';
$labels['invalid_email'] = 'Invalid e-mail address';
