<?php
/* French translation for qmailforward plugin */

$labels['manage-forward'] = 'Transfert';
$labels['page-title']     = 'Transfert';
$labels['forward']  = 'Transfert';
$labels['redirect'] = 'Réacheminer à';
$labels['copy']     = 'Envoyer une copie à';
$labels['on']       = 'Actif';
$labels['off']      = 'Inactif';
$labels['status']   = 'État:';
$labels['action']   = 'Pour les courriels entrants, exécuter l’action suivante :';
$labels['saving']   = 'Enregistrement...';
$labels['success']  = 'Enregistré avec succès';
$labels['failed']   = 'Erreur lors de l\'enregistrement dans la base de données';
$labels['invalid_email'] = 'Adresse de courriel invalide';
