<?php
/* italian translation for qmailforward plugin */

$labels['manage-forward'] = 'Gestisci le impostazioni dell\'inoltro';
$labels['page-title']     = 'Gestione dell\'inoltro';

$labels['forward']  = 'Inoltro';
$labels['redirect'] = 'Reindirizza a';
$labels['copy']     = 'Invia copia a';
$labels['on']       = 'Attivato';
$labels['off']      = 'Disattivato';
$labels['status']   = 'Stato:';
$labels['action']   = 'Esegui le seguenti azioni all\'arrivo di messaggi di posta:';
$labels['saving']   = 'Salvataggio...';
$labels['success']  = 'Salvataggio avvenuto con successo';
$labels['failed']   = 'Errore durante il salvataggio dei dati';

$labels['invalid_email'] = 'Indirizzo e-mail non valido';
