<?php
/* russian translation for qmailforward plugin (thanks Mike) */

$labels['manage-forward'] = 'Настройки переадресации';
$labels['page-title']     = 'Настройки переадресации';
$labels['forward']  = 'Переадресация почты';
$labels['redirect'] = 'Перенаправить на';
$labels['copy']     = 'Отправить копию на';
$labels['on']       = 'Включено';
$labels['off']      = 'Выключено';
$labels['status']   = 'Состояние:';
$labels['action']   = 'Действия с входящим сообщением:';
$labels['saving']   = 'Сохарнение...';
$labels['success']  = 'Успешно';
$labels['failed']   = 'Ошибка записи в базу данных';
$labels['invalid_email'] = 'Неправильный e-mail адрес';
